export const currencyByRupee: Currency[] = [
    {
      name: 'Indian Rupee',
      value: 1.0,
      flag: '🇮🇳',
      symbol: '₹',
    },
    {
    name: 'DOLLAR',
    value: 0.012271428,
    flag: '🇺🇸',
    symbol: '$',
  },
  {
    name: 'EURO',
    value: 0.01125809,
    flag: '🇪🇺',
    symbol: '€',
  },
  {
    name: 'POUND',
    value: 0.0099194378,
    flag: '🇬🇧',
    symbol: '£',
  },
  {
    name: 'RUBEL',
    value: 0.85040469,
    flag: '🇷🇺',
    symbol: '₽',
  },
  {
    name: 'AUS DOLLAR',
    value: 0.01732574,
    flag: '🇦🇺',
    symbol: 'A$',
  },
  {
    name: 'CAN DOLLAR',
    value: 0.016457908,
    flag: '🇨🇦',
    symbol: 'C$',
  },
  {
    name: 'YEN',
    value: 1.5909089,
    flag: '🇯🇵',
    symbol: '¥',
  },
  {
    name: 'DINAR',
    value: 0.0037446993,
    flag: '🇰🇼',
    symbol: 'KD',
  },
  {
    name: 'BITCOIN',
    value: 0.000000543544886,
    flag: '🎰',
    symbol: '₿',
  },
  {
    name: 'Swiss Franc',
    value: 0.011318057,
    flag: '🇨🇭',
    symbol: 'CHF',
  },
  {
    name: 'Singapore Dollar',
    value: 0.016557847,
    flag: '🇸🇬',
    symbol: 'S$',
  },
  {
    name: 'Hong Kong Dollar',
    value: 0.096072352,
    flag: '🇭🇰',
    symbol: 'HK$',
  },
  {
    name: 'New Zealand Dollar',
    value: 0.019034245,
    flag: '🇳🇿',
    symbol: 'NZ$',
  },
  {
    name: 'Danish Krone',
    value: 0.083642,
    flag: '🇩🇰',
    symbol: 'DKK',
  },
  {
    name: 'Norwegian Krone',
    value: 0.11618,
    flag: '🇳🇴',
    symbol: 'NOK',
  },
  {
    name: 'Swedish Krona',
    value: 0.11067,
    flag: '🇸🇪',
    symbol: 'SEK',
  },
  {
    name: 'South African Rand',
    value: 0.22998,
    flag: '🇿🇦',
    symbol: 'ZAR',
  },
  {
    name: 'Thai Baht',
    value: 0.43429,
    flag: '🇹🇭',
    symbol: 'THB',
  },
  {
    name: 'Malaysian Ringgit',
    value: 0.05142,
    flag: '🇲🇾',
    symbol: 'MYR',
  },
  {
    name: 'Philippine Peso',
    value: 0.68825,
    flag: '🇵🇭',
    symbol: '₱',
  },
  {
    name: 'Brazilian Real',
    value: 0.06126,
    flag: '🇧🇷',
    symbol: 'R$',
  },
  {
    name: 'Indonesian Rupiah',
    value: 183.29,
    flag: '🇮🇩',
    symbol: 'Rp',
  },
  {
    name: 'Vietnamese Dong',
    value: 276.66,
    flag: '🇻🇳',
    symbol: '₫',
  },
  {
    name: 'Mexican Peso',
    value: 0.22876,
    flag: '🇲🇽',
    symbol: 'MX$',
  },
  {
    name: 'Turkish Lira',
    value: 0.33578,
    flag: '🇹🇷',
    symbol: '₺',
  },
  {
    name: 'Israeli New Shekel',
    value: 0.04547,
    flag: '🇮🇱',
    symbol: '₪',
  },
  {
    name: 'Colombian Peso',
    value: 55.07,
    flag: '🇨🇴',
    symbol: 'COL$',
  },
  {
    name: 'Peruvian Sol',
    value: 0.04613,
    flag: '🇵🇪',
    symbol: 'S/.',
  },
  {
    name: 'Bangladeshi Taka',
    value: 1.0624,
    flag: '🇧🇩',
    symbol: '৳',
  },
  {
    name: 'Pakistani Rupee',
    value: 3.0769,
    flag: '🇵🇰',
    symbol: '₨',
  },
  {
    name: 'Sri Lankan Rupee',
    value: 2.7241,
    flag: '🇱🇰',
    symbol: 'Rs',
  },
  {
    name: 'UAE Dirham',
    value: 0.045022,
    flag: '🇦🇪',
    symbol: 'د.إ',
  },
  {
    name: 'Czech Koruna',
    value: 0.28355,
    flag: '🇨🇿',
    symbol: 'Kč',
  },
  {
    name: 'Hungarian Forint',
    value: 4.3271,
    flag: '🇭🇺',
    symbol: 'Ft',
  },
  {
    name: 'Romanian Leu',
    value: 0.05938,
    flag: '🇷🇴',
    symbol: 'lei',
  },
  {
    name: 'Bulgarian Lev',
    value: 0.02277,
    flag: '🇧🇬',
    symbol: 'лв',
  },
  {
    name: 'Croatian Kuna',
    value: 0.09345,
    flag: '🇭🇷',
    symbol: 'kn',
  },
  {
    name: 'Icelandic Króna',
    value: 1.6913,
    flag: '🇮🇸',
    symbol: 'kr',
  },
  {
    name: 'Kazakhstani Tenge',
    value: 5.6475,
    flag: '🇰🇿',
    symbol: '₸',
  },
  {
    name: 'Serbian Dinar',
    value: 1.4405,
    flag: '🇷🇸',
    symbol: 'дин.',
  },
  {
    name: 'Lebanese Pound',
    value: 18423.33,
    flag: '🇱🇧',
    symbol: 'ل.ل',
  },
  {
    name: 'Jordanian Dinar',
    value: 0.00849,
    flag: '🇯🇴',
    symbol: 'د.أ',
  },
  {
    name: 'Omani Rial',
    value: 0.00468,
    flag: '🇴🇲',
    symbol: 'ر.ع.',
  },
  {
    name: 'Bahraini Dinar',
    value: 0.00462,
    flag: '🇧🇭',
    symbol: '.د.ب',
  },
  {
    name: 'Qatari Rial',
    value: 0.04574,
    flag: '🇶🇦',
    symbol: 'ر.ق',
  },
  {
    name: 'Algerian Dinar',
    value: 1.6358,
    flag: '🇩🇿',
    symbol: 'د.ج',
  },
  {
    name: 'Moroccan Dirham',
    value: 0.1297,
    flag: '🇲🇦',
    symbol: 'د.م.',
  },
  {
    name: 'Tunisian Dinar',
    value: 0.03731,
    flag: '🇹🇳',
    symbol: 'د.ت',
  },
  {
    name: 'Mauritian Rupee',
    value: 0.55668,
    flag: '🇲🇺',
    symbol: '₨',
  },
  {
    name: 'Rwandan Franc',
    value: 15.87,
    flag: '🇷🇼',
    symbol: 'FRW',
  },
  {
    name: 'Ugandan Shilling',
    value: 46.54,
    flag: '🇺🇬',
    symbol: 'USh',
  },
  {
    name: 'Tanzanian Shilling',
    value: 30.42,
    flag: '🇹🇿',
    symbol: 'TSh',
  },
  {
    name: 'Zambian Kwacha',
    value: 0.207,
    flag: '🇿🇲',
    symbol: 'ZK',
  },
  {
    name: 'Botswana Pula',
    value: 0.129,
    flag: '🇧🇼',
    symbol: 'P',
  },
  {
    name: 'Ghanaian Cedi',
    value: 0.135,
    flag: '🇬🇭',
    symbol: '₵',
  },
  {
    name: 'Nigerian Naira',
    value: 6.94,
    flag: '🇳🇬',
    symbol: '₦',
  },
  {
    name: 'Kyrgyzstani Som',
    value: 1.067,
    flag: '🇰🇬',
    symbol: 'с',
  },
  {
    name: 'Uzbekistani Som',
    value: 14226.55,
    flag: '🇺🇿',
    symbol: 'лв',
  },
  {
    name: 'Mongolian Tögrög',
    value: 45.34,
    flag: '🇲🇳',
    symbol: '₮',
  },
  {
    name: 'Afghan Afghani',
    value: 1.054,
    flag: '🇦🇫',
    symbol: '؋',
  },
];
